fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

twitter_api:
    resource: "@TwitterApiBundle/Resources/config/routing.yml"
    prefix:   /api/v0

